version: '3'

volumes: 
  mariadb_data:
    driver: local

networks:
  backend:
    driver: bridge

services:

  get:
    build: ./app
    container_name: getdata
    environment:
      DB_HOST: mariadb
      DB_NAME: shares
      DB_USER: fen9li
      DB_PASS: changeme
    volumes:
      - ${PWD}/app:/app
    networks:
      - backend
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - backend
    ports:
      - '8080:80'
    volumes:
      - /sessions
      - ${PWD}/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: shares
      MYSQL_USER: fen9li
      MYSQL_PASSWORD: changeme
    networks:
      - backend
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
  